//! Static assets and generated files written into a new Evidence dashboard project.

use std::path::{Path, PathBuf};

use crate::cli::config::DatabaseConfig;
use crate::dashboard::Dashboard;

/// Which database flavor a scaffolded dashboard targets. Single source of
/// truth for per-database strings substituted into templates (Evidence
/// source name, datasource plugin id, etc.). Derive once from
/// [`DatabaseConfig`] with [`DatasourceKind::from_database`] and pass
/// downstream instead of N parallel `&str`s.
#[derive(Debug, Clone, Copy)]
pub enum DatasourceKind {
    DuckDb,
    Postgres,
    ClickHouse,
}

impl DatasourceKind {
    /// Pick the kind from a [`DatabaseConfig`]. Returns `None` if no
    /// database backend is configured.
    pub fn from_database(db: &DatabaseConfig) -> Option<Self> {
        if db.duckdb.is_some() {
            Some(Self::DuckDb)
        } else if db.postgresql.is_some() {
            Some(Self::Postgres)
        } else if db.clickhouse.is_some() {
            Some(Self::ClickHouse)
        } else {
            None
        }
    }

    /// Evidence source name — schema prefix in page queries and the
    /// directory name under `sources/`.
    pub fn source_name(self) -> &'static str {
        match self {
            Self::DuckDb => "local_duckdb",
            Self::Postgres => "pg",
            Self::ClickHouse => "clickhouse",
        }
    }

    /// npm package id of the Evidence datasource plugin, written into
    /// `evidence.config.yaml` under `plugins.datasources`.
    pub fn evidence_plugin(self) -> &'static str {
        match self {
            Self::DuckDb => "@evidence-dev/duckdb",
            Self::Postgres => "@evidence-dev/postgres",
            Self::ClickHouse => "evidence-connector-clickhouse",
        }
    }

    /// `"<plugin>": "<semver>"` JSON line injected into `package.json`'s
    /// `dependencies` so `npm install` pulls the right Evidence connector.
    pub fn evidence_plugin_dependency(self) -> &'static str {
        match self {
            Self::DuckDb => "\"@evidence-dev/duckdb\": \"^2.0.1\"",
            Self::Postgres => "\"@evidence-dev/postgres\": \"^1.0.10\"",
            Self::ClickHouse => "\"evidence-connector-clickhouse\": \"^0.0.2\"",
        }
    }
}

static LANDING_PAGE_HTML: &str = include_str!("templates/landing_page.html");

/// Renders a static `index.html` snapshot of the enabled dashboard list.
/// Returns the destination filename and fully-rendered HTML content.
pub fn render_landing_page_file(dashboards: &[&Dashboard]) -> (PathBuf, String) {
    use std::fmt::Write as _;
    let mut list = String::new();
    if dashboards.is_empty() {
        let _ = list.write_str(
            "<p class=\"empty\">No dashboards are configured yet. Add a \
             <code>dashboards:</code> entry to your YAML config and run \
             <code>tiders-x402-server dashboard &lt;slug&gt;</code> to scaffold one.</p>",
        );
    } else {
        let _ = list.write_str("<ul class=\"dashboards\">");
        for d in dashboards {
            let slug = html_escape(&d.slug);
            let title = html_escape(&d.title);
            let _ = write!(
                list,
                "<li><a href=\"/{slug}/\"><span class=\"dashboard-title\">{title}<span class=\"arrow\">\u{2192}</span></span>"
            );
            if let Some(desc) = &d.description {
                let _ = write!(
                    list,
                    "<p class=\"dashboard-desc\">{}</p>",
                    html_escape(desc)
                );
            }
            if !d.tags.is_empty() {
                let _ = list.write_str("<div class=\"dashboard-tags\">");
                for tag in &d.tags {
                    let _ = write!(
                        list,
                        "<span class=\"dashboard-tag\">{}</span>",
                        html_escape(tag)
                    );
                }
                let _ = list.write_str("</div>");
            }
            let _ = list.write_str("</a></li>");
        }
        let _ = list.write_str("</ul>");
    }
    (
        PathBuf::from("index.html"),
        LANDING_PAGE_HTML.replace("<!--DASHBOARD_LIST-->", &list),
    )
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CONNECTION_HEADER: &str =
    "# Generated by tiders-x402-server. Regenerate with `dashboard <name> --force`.\n";

/// Generates the Evidence `sources/<dir>/connection.yaml` for the configured database.
///
/// DuckDB only: `filename` must be relative to `project_dir/sources/<dir>/` due to Evidence's implementation of the DuckDB connector.
pub fn render_connection_files(db: &DatabaseConfig, project_dir: &Path) -> Vec<(PathBuf, String)> {
    if let Some(duck) = &db.duckdb {
        let connection_dir = project_dir.join("sources/local_duckdb");
        let db_filename = relative_path(&connection_dir, &duck.path);
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: local_duckdb\n\
             type: duckdb\n\
             options:\n  filename: {}\n  access_mode: READ_ONLY\n",
            db_filename.display()
        );
        return vec![(PathBuf::from("sources/local_duckdb/connection.yaml"), yaml)];
    }

    if let Some(pg) = &db.postgresql {
        let parsed = parse_pg_connection_string(&pg.connection_string);
        let get = |k: &str| parsed.get(k).map(String::as_str).unwrap_or("");
        let database = parsed
            .get("dbname")
            .or_else(|| parsed.get("database"))
            .map(String::as_str)
            .unwrap_or("");
        let host = get("host");
        let port = get("port");
        let user = get("user");
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: pg\n\
             type: postgres\n\
             options:\n  \
             host: {host}\n  \
             port: {port}\n  \
             user: {user}\n  \
             database: {database}\n\
             # The password is intentionally omitted. Evidence does not allow passing passwords through the connection file to avoid exposing them in the file system.\n\
             # Evidence reads it from the EVIDENCE_SOURCE__pg__password env var. Set it in a .env file in this dashboard's directory or in the build-time environment.\n",
        );
        return vec![(PathBuf::from("sources/pg/connection.yaml"), yaml)];
    }

    if let Some(ch) = &db.clickhouse {
        let username = ch.user.as_deref().unwrap_or("default");
        let url = &ch.url;
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: clickhouse\n\
             type: clickhouse\n\
             options:\n  \
             url: {url}\n  \
             username: {username}\n\
             # The password is intentionally omitted. Evidence does not allow passing passwords through the connection file to avoid exposing them in the file system.\n\
             # Evidence reads it from the EVIDENCE_SOURCE__clickhouse__password env var. Set it in a .env file in this dashboard's directory or in the build-time environment.\n",
        );
        return vec![(PathBuf::from("sources/clickhouse/connection.yaml"), yaml)];
    }

    vec![]
}

/// Generates one `sources/<source_name>/<table>.sql` file per table.
/// Each file contains `select * from <qualified-table> limit 10` so
/// `evidence sources` extracts a sample of every table into Parquet for the
/// dashboard to query.
pub fn render_sql_files(db: &DatabaseConfig, tables: &[&str]) -> Vec<(PathBuf, String)> {
    let Some(datasource) = DatasourceKind::from_database(db) else {
        return vec![];
    };
    let source_name = datasource.source_name();
    let database = database_qualifier(db);
    tables
        .iter()
        .map(|table| {
            let path = PathBuf::from(format!("sources/{source_name}/{table}.sql"));
            let qualified = match &database {
                Some(d) => format!("{d}.{table}"),
                None => table.to_string(),
            };
            let sql = format!("select * from {qualified} limit 10\n");
            (path, sql)
        })
        .collect()
}

/// Database name used to qualify table references in generated `*.sql`
/// files. DuckDB doesn't use a database qualifier; postgres pulls `dbname`
/// from the connection string; clickhouse uses the configured `database`
/// (falling back to `default`).
fn database_qualifier(db: &DatabaseConfig) -> Option<String> {
    if db.duckdb.is_some() {
        return None;
    }
    if let Some(pg) = &db.postgresql {
        let parsed = parse_pg_connection_string(&pg.connection_string);
        return parsed
            .get("dbname")
            .or_else(|| parsed.get("database"))
            .cloned();
    }
    if let Some(ch) = &db.clickhouse {
        return Some(ch.database.clone().unwrap_or_else(|| "default".into()));
    }
    None
}

/// One embedded template file written to the dashboard project by the scaffolder.
///
/// Most templates are fixed boilerplate (Svelte components, npm config); a
/// few contain `{{SLUG}}` / `{{TITLE}}` / `{{SEED_TABLE}}` / `{{SOURCE_NAME}}`
/// placeholders that [`render`] substitutes at scaffold time. Every template
/// in [`TEMPLATES`] is treated as managed — overwritten on `--force` (with
/// drift detection backing up user-edited copies to `.old/`).
pub struct Template {
    /// Path relative to the dashboard project root (e.g. `components/lib/wagmi.ts`).
    pub path: &'static str,
    /// Raw template contents, embedded into the binary via `include_str!`.
    pub contents: &'static str,
    /// Whether [`render`] should run placeholder substitution on `contents`.
    pub substitute: bool,
}

/// All managed templates written on every scaffold run.
pub const TEMPLATES: &[Template] = &[
    Template {
        path: ".npmrc",
        contents: include_str!("templates/.npmrc"),
        substitute: false,
    },
    Template {
        path: ".gitignore",
        contents: include_str!("templates/.gitignore"),
        substitute: false,
    },
    Template {
        path: "package.json",
        contents: include_str!("templates/package.json"),
        substitute: true,
    },
    Template {
        path: "evidence.config.yaml",
        contents: include_str!("templates/evidence.config.yaml"),
        substitute: true,
    },
    Template {
        path: "pages/+layout.svelte",
        contents: include_str!("templates/pages/+layout.svelte"),
        substitute: false,
    },
    Template {
        path: "components/ConnectButton.svelte",
        contents: include_str!("templates/components/ConnectButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/WalletPicker.svelte",
        contents: include_str!("templates/components/WalletPicker.svelte"),
        substitute: false,
    },
    Template {
        path: "components/TidersDownloadButton.svelte",
        contents: include_str!("templates/components/TidersDownloadButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/TidersDownloadModal.svelte",
        contents: include_str!("templates/components/TidersDownloadModal.svelte"),
        substitute: false,
    },
    Template {
        path: "components/lib/eip6963.ts",
        contents: include_str!("templates/components/lib/eip6963.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/arrowToCsv.ts",
        contents: include_str!("templates/components/lib/arrowToCsv.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/wagmi.ts",
        contents: include_str!("templates/components/lib/wagmi.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/walletStore.ts",
        contents: include_str!("templates/components/lib/walletStore.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/x402Client.ts",
        contents: include_str!("templates/components/lib/x402Client.ts"),
        substitute: false,
    },
];

/// `STARTER_INDEX_MD` is a special case written only when the file does not yet
/// exist so the user's edits to `pages/index.md` survive re-runs.
pub const STARTER_INDEX_MD: &str = include_str!("templates/pages/index.md");

/// Fills template placeholders: `{{SLUG}}`, `{{TITLE}}`, `{{SEED_TABLE}}`,
/// `{{SOURCE_NAME}}`, and `{{DATASOURCE_PLUGIN}}`.
pub fn render(
    contents: &str,
    slug: &str,
    title: &str,
    seed_table: &str,
    datasource: DatasourceKind,
) -> String {
    contents
        .replace("{{SLUG}}", slug)
        .replace("{{TITLE}}", title)
        .replace("{{SEED_TABLE}}", seed_table)
        .replace("{{SOURCE_NAME}}", datasource.source_name())
        .replace("{{DATASOURCE_PLUGIN}}", datasource.evidence_plugin())
        .replace(
            "{{DATASOURCE_PLUGIN_DEPENDENCY}}",
            datasource.evidence_plugin_dependency(),
        )
}

/// Parses a libpq-style `key=value key=value ...` postgres connection string
/// into a map. Values may contain `${VAR}` references — those are preserved
/// verbatim and resolved later by whoever consumes the YAML. Quoted values
/// and escapes are not supported (the server config doesn't use them).
fn parse_pg_connection_string(s: &str) -> std::collections::HashMap<String, String> {
    let mut map = std::collections::HashMap::new();
    for token in s.split_whitespace() {
        if let Some((k, v)) = token.split_once('=') {
            map.insert(k.to_string(), v.to_string());
        }
    }
    map
}

/// Computes a relative path from directory `from` to file `to`.
fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from
        .iter()
        .zip(to.iter())
        .take_while(|(a, b)| a == b)
        .count();
    let mut rel = PathBuf::new();
    for _ in 0..(from.len() - common) {
        rel.push("..");
    }
    for part in &to[common..] {
        rel.push(part);
    }
    rel
}
