//! Static assets and generated files written into a new Evidence dashboard project.

use std::path::{Path, PathBuf};

use crate::cli::config::DatabaseConfig;
use crate::dashboard::Dashboard;


static LANDING_PAGE_HTML: &str = include_str!("templates/landing_page.html");

/// Renders a static `index.html` snapshot of the enabled dashboard list.
/// Returns the destination filename and fully-rendered HTML content.
pub fn render_landing_page_file(dashboards: &[&Dashboard]) -> (PathBuf, String) {
    use std::fmt::Write as _;
    let mut list = String::new();
    if dashboards.is_empty() {
        let _ = list.write_str(
            "<p class=\"empty\">No dashboards are configured yet. Add a \
             <code>dashboards:</code> entry to your YAML config and run \
             <code>tiders-x402-server dashboard &lt;slug&gt;</code> to scaffold one.</p>",
        );
    } else {
        let _ = list.write_str("<ul class=\"dashboards\">");
        for d in dashboards {
            let slug = html_escape(&d.slug);
            let title = html_escape(&d.title);
            let _ = write!(
                list,
                "<li><a href=\"/{slug}/\"><span class=\"dashboard-title\">{title}<span class=\"arrow\">\u{2192}</span></span>"
            );
            if let Some(desc) = &d.description {
                let _ = write!(list, "<p class=\"dashboard-desc\">{}</p>", html_escape(desc));
            }
            if !d.tags.is_empty() {
                let _ = list.write_str("<div class=\"dashboard-tags\">");
                for tag in &d.tags {
                    let _ = write!(list, "<span class=\"dashboard-tag\">{}</span>", html_escape(tag));
                }
                let _ = list.write_str("</div>");
            }
            let _ = list.write_str("</a></li>");
        }
        let _ = list.write_str("</ul>");
    }
    (
        PathBuf::from("index.html"),
        LANDING_PAGE_HTML.replace("<!--DASHBOARD_LIST-->", &list),
    )
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CONNECTION_HEADER: &str =
    "# Generated by tiders-x402-server. Regenerate with `dashboard <name> --force`.\n";

/// Generates the Evidence `sources/<dir>/connection.yaml` for the configured database.
///
/// DuckDB only: `filename` must be relative to `project_dir/sources/<dir>/` due to Evidence's implementation of the DuckDB connector.
pub fn render_connection_files(
    db: &DatabaseConfig,
    project_dir: &Path,
) -> Vec<(PathBuf, String)> {
    if let Some(duck) = &db.duckdb {
        let connection_dir = project_dir.join("sources/local_duckdb");
        let db_filename = relative_path(&connection_dir, &duck.path);
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: local_duckdb\n\
             type: duckdb\n\
             options:\n  filename: {}\n  access_mode: READ_ONLY\n",
            db_filename.display()
        );
        return vec![(PathBuf::from("sources/local_duckdb/connection.yaml"), yaml)];
    }

    if let Some(pg) = &db.postgresql {
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: pg\n\
             type: postgres\n\
             # Edit the values below to match your dashboard's read-only role.\n\
             # The server's connection_string is shown for reference:\n\
             #   {}\n\
             options:\n  host: localhost\n  port: 5432\n  user: postgres\n  database: postgres\n  password: ${{PG_PASSWORD}}\n",
            pg.connection_string
        );
        return vec![(PathBuf::from("sources/pg/connection.yaml"), yaml)];
    }

    if let Some(ch) = &db.clickhouse {
        let user = ch.user.as_deref().unwrap_or("default");
        let database = ch.database.as_deref().unwrap_or("default");
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: clickhouse\n\
             type: clickhouse\n\
             options:\n  url: {}\n  user: {user}\n  database: {database}\n  password: ${{CLICKHOUSE_PASSWORD}}\n",
            ch.url
        );
        return vec![(PathBuf::from("sources/clickhouse/connection.yaml"), yaml)];
    }

    vec![]
}

/// Generates one `sources/<source_name>/<table>.sql` file per table.
/// Each file contains `select * from <table> limit 10` so `evidence sources`
/// extracts a sample of every table into Parquet for the dashboard to query.
pub fn render_sql_files(source_name: &str, tables: &[&str]) -> Vec<(PathBuf, String)> {
    tables
        .iter()
        .map(|table| {
            let path = PathBuf::from(format!("sources/{source_name}/{table}.sql"));
            let sql = format!("select * from {table} limit 10\n");
            (path, sql)
        })
        .collect()
}

/// One embedded template.
/// Files written to the dashboard directory by the scaffolder. Most are fixed
/// boilerplate (Svelte components, npm config), but a
/// few contain `{{SLUG}}` / `{{SEED_TABLE}}` placeholders that are filled in
/// by `render` at scaffold time. Managed files are always overwritten on
/// `--force`; 
/// 
/// path: its path relative to the dashboard folder
/// contents: its raw contents
/// substitute: whether variable substitution are needed.
pub struct Template {
    pub path: &'static str,
    pub contents: &'static str,
    pub substitute: bool,
}

/// All managed templates written on every scaffold run.
pub const TEMPLATES: &[Template] = &[
    Template {
        path: ".npmrc",
        contents: include_str!("templates/.npmrc"),
        substitute: false,
    },
    Template {
        path: ".gitignore",
        contents: include_str!("templates/.gitignore"),
        substitute: false,
    },
    Template {
        path: "package.json",
        contents: include_str!("templates/package.json"),
        substitute: true,
    },
    Template {
        path: "evidence.config.yaml",
        contents: include_str!("templates/evidence.config.yaml"),
        substitute: true,
    },
    Template {
        path: "pages/+layout.svelte",
        contents: include_str!("templates/pages/+layout.svelte"),
        substitute: false,
    },
    Template {
        path: "components/ConnectButton.svelte",
        contents: include_str!("templates/components/ConnectButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/WalletPicker.svelte",
        contents: include_str!("templates/components/WalletPicker.svelte"),
        substitute: false,
    },
    Template {
        path: "components/TidersDownloadButton.svelte",
        contents: include_str!("templates/components/TidersDownloadButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/TidersDownloadModal.svelte",
        contents: include_str!("templates/components/TidersDownloadModal.svelte"),
        substitute: false,
    },
    Template {
        path: "components/lib/eip6963.ts",
        contents: include_str!("templates/components/lib/eip6963.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/arrowToCsv.ts",
        contents: include_str!("templates/components/lib/arrowToCsv.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/wagmi.ts",
        contents: include_str!("templates/components/lib/wagmi.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/walletStore.ts",
        contents: include_str!("templates/components/lib/walletStore.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/x402Client.ts",
        contents: include_str!("templates/components/lib/x402Client.ts"),
        substitute: false,
    },
];

/// `STARTER_INDEX_MD` is a special case written only when the file does not yet
/// exist so the user's edits to `pages/index.md` survive re-runs.
pub const STARTER_INDEX_MD: &str = include_str!("templates/pages/index.md");

/// Fills `{{SLUG}}`, `{{SEED_TABLE}}`, and `{{SOURCE_NAME}}` placeholders in a template.
pub fn render(contents: &str, slug: &str, title: &str, seed_table: &str, source_name: &str) -> String {
    contents
        .replace("{{SLUG}}", slug)
        .replace("{{TITLE}}", title)
        .replace("{{SEED_TABLE}}", seed_table)
        .replace("{{SOURCE_NAME}}", source_name)
}

/// Computes a relative path from directory `from` to file `to`.
fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from.iter().zip(to.iter()).take_while(|(a, b)| a == b).count();
    let mut rel = PathBuf::new();
    for _ in 0..(from.len() - common) {
        rel.push("..");
    }
    for part in &to[common..] {
        rel.push(part);
    }
    rel
}
