//! Static assets and generated files written into a new Evidence dashboard project.

use std::path::{Path, PathBuf};

use crate::cli::config::DatabaseConfig;

const CONNECTION_HEADER: &str =
    "# Generated by tiders-x402-server. Regenerate with `dashboard <name> --force`.\n";

/// Generates the Evidence source files for the dashboard's database connection.
///
/// Evidence's build model has two phases:
/// 1. `evidence sources` — runs `.sql` files in `sources/<name>/` against the
///    live database connector and writes Parquet files.
/// 2. `evidence build` — loads those Parquet files into an in-memory DuckDB
///    and evaluates page queries against it using the source name as the schema
///    prefix (e.g. `local_duckdb.table_name`).
///
/// This function returns `connection.yaml` (the connector config) plus a seed
/// `.sql` file that extracts the first configured table so `evidence sources`
/// produces data and the starter page has something to display.
///
/// DuckDB only: `filename` must be relative to `source.dir`
/// (`<project_dir>/sources/local_duckdb/`) because Evidence's connector uses
/// Node's `path.join(directory, filename)`, which silently strips the leading
/// `/` from absolute paths.
/// Returns `(files, source_name)` where `source_name` is the Evidence schema
/// prefix used in page queries (e.g. `local_duckdb`, `pg`, `clickhouse`).
pub fn render_connection_files(
    db: &DatabaseConfig,
    project_dir: &Path,
    seed_table: &str,
) -> (Vec<(PathBuf, String)>, String) {
    if let Some(duck) = &db.duckdb {
        let connection_dir = project_dir.join("sources/local_duckdb");
        let db_filename = relative_path(&connection_dir, &duck.path);
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: local_duckdb\n\
             type: duckdb\n\
             options:\n  filename: {}\n  access_mode: READ_ONLY\n",
            db_filename.display()
        );
        let sql = format!("select * from {seed_table} limit 1000\n");
        return (
            vec![
                (PathBuf::from("sources/local_duckdb/connection.yaml"), yaml),
                (PathBuf::from(format!("sources/local_duckdb/{seed_table}.sql")), sql),
            ],
            "local_duckdb".to_string(),
        );
    }

    if let Some(pg) = &db.postgresql {
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: pg\n\
             type: postgres\n\
             # Edit the values below to match your dashboard's read-only role.\n\
             # The server's connection_string is shown for reference:\n\
             #   {}\n\
             options:\n  host: localhost\n  port: 5432\n  user: postgres\n  database: postgres\n  password: ${{PG_PASSWORD}}\n",
            pg.connection_string
        );
        let sql = format!("select * from {seed_table} limit 1000\n");
        return (
            vec![
                (PathBuf::from("sources/pg/connection.yaml"), yaml),
                (PathBuf::from(format!("sources/pg/{seed_table}.sql")), sql),
            ],
            "pg".to_string(),
        );
    }

    if let Some(ch) = &db.clickhouse {
        let user = ch.user.as_deref().unwrap_or("default");
        let database = ch.database.as_deref().unwrap_or("default");
        let yaml = format!(
            "{CONNECTION_HEADER}\
             name: clickhouse\n\
             type: clickhouse\n\
             options:\n  url: {}\n  user: {user}\n  database: {database}\n  password: ${{CLICKHOUSE_PASSWORD}}\n",
            ch.url
        );
        let sql = format!("select * from {seed_table} limit 1000\n");
        return (
            vec![
                (PathBuf::from("sources/clickhouse/connection.yaml"), yaml),
                (PathBuf::from(format!("sources/clickhouse/{seed_table}.sql")), sql),
            ],
            "clickhouse".to_string(),
        );
    }

    (vec![], String::new())
}

/// One embedded template.
/// Files written to the dashboard directory by the scaffolder. Most are fixed
/// boilerplate (Svelte components, npm config), but a
/// few contain `{{NAME}}` / `{{SEED_TABLE}}` placeholders that are filled in
/// by `render` at scaffold time. Managed files are always overwritten on
/// `--force`; 
/// 
/// path: its path relative to the dashboard folder
/// contents: its raw contents
/// substitute: whether variable substitution are needed.
pub struct Template {
    pub path: &'static str,
    pub contents: &'static str,
    pub substitute: bool,
}

/// All managed templates written on every scaffold run.
pub const TEMPLATES: &[Template] = &[
    Template {
        path: ".npmrc",
        contents: include_str!("templates/.npmrc"),
        substitute: false,
    },
    Template {
        path: ".gitignore",
        contents: include_str!("templates/.gitignore"),
        substitute: false,
    },
    Template {
        path: "package.json",
        contents: include_str!("templates/package.json"),
        substitute: true,
    },
    Template {
        path: "evidence.config.yaml",
        contents: include_str!("templates/evidence.config.yaml"),
        substitute: true,
    },
    Template {
        path: "pages/+layout.svelte",
        contents: include_str!("templates/pages/+layout.svelte"),
        substitute: true,
    },
    Template {
        path: "components/ConnectButton.svelte",
        contents: include_str!("templates/components/ConnectButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/PaidDownloadButton.svelte",
        contents: include_str!("templates/components/PaidDownloadButton.svelte"),
        substitute: false,
    },
    Template {
        path: "components/PaidDownloadModal.svelte",
        contents: include_str!("templates/components/PaidDownloadModal.svelte"),
        substitute: false,
    },
    Template {
        path: "components/lib/arrowToCsv.ts",
        contents: include_str!("templates/components/lib/arrowToCsv.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/wagmi.ts",
        contents: include_str!("templates/components/lib/wagmi.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/walletStore.ts",
        contents: include_str!("templates/components/lib/walletStore.ts"),
        substitute: false,
    },
    Template {
        path: "components/lib/x402Client.ts",
        contents: include_str!("templates/components/lib/x402Client.ts"),
        substitute: false,
    },
];

/// `STARTER_INDEX_MD` is a special case written only when the file does not yet
/// exist so the user's edits to `pages/index.md` survive re-runs.
pub const STARTER_INDEX_MD: &str = include_str!("templates/pages/index.md");

/// Fills `{{NAME}}`, `{{SEED_TABLE}}`, and `{{SOURCE_NAME}}` placeholders in a template.
pub fn render(contents: &str, name: &str, seed_table: &str, source_name: &str) -> String {
    contents
        .replace("{{NAME}}", name)
        .replace("{{SEED_TABLE}}", seed_table)
        .replace("{{SOURCE_NAME}}", source_name)
}

/// Computes a relative path from directory `from` to file `to`.
fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from.iter().zip(to.iter()).take_while(|(a, b)| a == b).count();
    let mut rel = PathBuf::new();
    for _ in 0..(from.len() - common) {
        rel.push("..");
    }
    for part in &to[common..] {
        rel.push(part);
    }
    rel
}
